<?php

namespace King_Addons;

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

final class CollectionsMap
{
    public static function getCollectionsMapArray(): array
    {
        return [
            1 => 'SaaS & IT Solutions',
            2 => 'Mobile App & Software',
            3 => 'NFT & Crypto',
            4 => 'AI and Chatbot',
            5 => 'Hosting Platform & Services',
            6 => 'SEO & Digital Marketing',
            7 => 'Business Consulting',
            8 => 'Digital Marketing',
            9 => 'Health Center',
            10 => 'Italian Restaurant',
            11 => 'Logistics Services',
            12 => 'Startup Landings',
            13 => 'Orthodontic & Dentist',
            14 => 'Building & Construction',
            15 => 'Online Business',
            16 => 'Animal Shelter',
            17 => 'Agriculture & Farm',
            18 => 'Textile & Manufacturing',
            19 => 'Church and Charity',
            20 => 'Dog Breeder',
            21 => 'Yoga and Fitness',
            22 => 'Auto Service',
            23 => 'Horse Riding Club',
            24 => 'Electrician Repair',
            25 => 'Law & Justice',
            26 => 'Prosthetics Medical Center',
            27 => 'Kindergarten & Preschool',
            28 => 'Metallurgy & Industry',
            29 => 'Beekeeping and Honey',
            30 => 'Senior Care',
            31 => 'Lash Extensions',
            32 => 'Flight School & Aviation',
            33 => 'Optometrist & Eye Care',
            34 => 'Oil & Gas Company',
            35 => 'Immigration & Visa Consulting',
            36 => 'Dermatology and Cosmetology',
            37 => 'Meat Store & Butcher',
            38 => 'Paving & Tiling Services',
            39 => 'Plastic Surgery Clinic',
            40 => 'Yacht Rental & Boat Service',
            41 => 'Handmade Soap & Candles Shop',
            42 => 'Heating & Air Conditioning',
            43 => 'Dental Clinic & Dentist',
            44 => 'Limousine & Car Rental',
            45 => 'Emergency Road Service',
            46 => 'Nail Bar & Beauty Salon',
            47 => 'Windows & Doors Installation',
            48 => 'Renewable Energy',
            49 => 'Wooden House Construction',
            50 => 'Laundry Service & Dry Cleaning',
            51 => 'Broadband Service',
            52 => 'Astrology & Numerology',
            53 => 'Driving School',
            54 => 'Water Sports',
            55 => 'Vape Shop and E-Liquids',
            56 => 'Car Washing Services',
            57 => 'Golf Club',
            58 => 'Hookah Lounge & Shisha Bar',
            59 => 'Tobacco Shop',
            60 => 'Coffee Shop & Cafe',
            61 => 'Camping and Adventure',
            62 => 'Water Delivery & Filtration',
            63 => 'Flower Shop & Florist',
            64 => 'Wedding Business',
            65 => 'Building & Construction Company',
            66 => 'Online Education Services',
            67 => 'Wine Shop & Vineyards',
            68 => 'Plumber & Handyman',
            69 => 'Barber & Haircut',
            70 => 'Insurance Agency',
            71 => 'Gym & Fitness',
            72 => 'Funeral Services',
            73 => 'Tattoo & Piercing Studio',
            74 => 'eSports Teams & Gaming Studio',
            75 => 'Security Guard',
        ];
    }
}